name: fakeflix
services:
  db:
    image: postgres:15-alpine
    container_name: fakeflix-db
    environment:
      - POSTGRES_USER=fakeflix
      - POSTGRES_PASSWORD=fakeflix
      - POSTGRES_DB=fakeflix
    ports:
      - '5432:5432'
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data
